### ISSUE TITLE
Wrong Requirements dependency declaration?!

### ISSUE THREAD

**Issue by mucic** [ubilabs/google-maps-react-hooks#38]
Documentation notes that "You need to have React 16.8.0 or later installed to use the Hooks API."

`package.json` dependency declaration is:

`  "peerDependencies": {
    "react": ">=16.18.0 <18.0.0"
  },`

Is 16.18.0 typo? This package is not working with react 16.14.0

**Comment by plumdumpling** [comment]
Thank you @mucic for pointing this out!
It should be `>=16.8.0`. A fix for this will be in the next version.
